default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: ecommerce_db_development
  username: postgres
  password:
  host: db
  port: 5432

test:
  <<: *default
  database: ecommerce_db_test
  username: postgres
  password:
  host: db
  port: 5432

production:
  <<: *default
  database: ecommerce_db_production
  username: postgres
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
